### ISSUE TITLE
SMAPI Not working

### ISSUE THREAD

**Issue by jameelamir2005** [ClxS/SMAPI#96] opened 2016-04-03 14:59 UTC
Hey, When i open the SMAPI, It shows me a CMD With some text that i cannot understand on it, and then when i open the game it just doesnt show the mod, i cant use it.. help

**Comment by jameelamir2005** [comment] 2016-04-03 14:59
That's what it shows me **C:\Users\HP\AppData\Roaming\StardewValley\ErrorLogs\MODDED_ProgramLog.Log_LATEST.txt
System.TypeInitializationException: The type initializer for 'StardewModdingAPI.Log' threw an exception. ---> System.IO.IOException: The process cannot access the file 'C:\Users\HP\AppData\Roaming\StardewValley\ErrorLogs\MODDED_ProgramLog.Log_LATEST.txt' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at StardewModdingAPI.LogWriter.get_Instance()
   at StardewModdingAPI.Log..cctor()
   --- End of inner exception stack trace ---
   at StardewModdingAPI.Log.AsyncY(Object message)
   at StardewModdingAPI.Program.Main(String[] args)
**

**Comment by Kithio** [comment] 2016-04-03 15:14
It seems like you're trying to start the API's exe file while it's already running.

If you do not see the window you should look in Task Manager for the process "StardewModdingAPI.exe" and force close it and try again.

**Comment by jameelamir2005** [comment] 2016-04-03 15:15
Thanks but, This is what i get now, a red and grey text
C:\Users\HP\AppData\Roaming\StardewValley\ErrorLogs\MODDED_ProgramLog.Log_LATEST.txt
Created log instance
[06:14:42.522 م] SMAPI Version: 0.39.6 Alpha
[06:14:42.522 م] SDV Version: 1.0
[06:14:42.522 م] Validating api paths...
[06:14:42.534 م] Injecting New SDV Version...
[06:14:42.534 م] Starting SDV...
[06:14:42.532 م] Initializing SDV Assembly...
[06:14:42.682 م] Patching SDV Graphics Profile...
[06:14:42.688 م] LOADING MODS
[06:14:42.689 م] Found Manifest: C:\Users\HP\AppData\Roaming\StardewValley\Mods\NPCMapLocations\manifest.json
[06:14:43.410 م] Created psconfigs directory @C:\Users\HP\AppData\Roaming\StardewValley\Mods\NPCMapLocations\psconfigs
[06:14:43.413 م] Loading Mod DLL...
[06:14:43.414 م] LOADED MOD: NPC Map Locations Mod by Bouhm - Version StardewModdingAPI.Version | Description: Shows NPC locations on the map (@ C:\Users\HP\AppData\Roaming\StardewValley\Mods\NPCMapLocations\NPCMapLocations.dll)
[06:14:43.460 م] Found Manifest: C:\Users\HP\AppData\Roaming\StardewValley\Mods\TrainerMod\manifest.json
[06:14:43.488 م] Created psconfigs directory @C:\Users\HP\AppData\Roaming\StardewValley\Mods\TrainerMod\psconfigs
[06:14:43.490 م] Loading Mod DLL...
[06:14:43.490 م] LOADED MOD: Trainer Mod by Zoryn - Version StardewModdingAPI.Version | Description: Registers several commands to use. Most commands are trainer-like in that they offer forms of cheating. (@ C:\Users\HP\AppData\Roaming\StardewValley\Mods\TrainerMod\TrainerMod.dll)
[06:14:43.494 م] Registered command: types
[06:14:43.497 م] Registered command: save
[06:14:43.497 م] Registered command: load
[06:14:43.498 م] Registered command: stop
[06:14:43.499 م] Registered command: player_setname
[06:14:43.499 م] Registered command: player_setmoney
[06:14:43.500 م] Registered command: player_setstamina
[06:14:43.497 م] Registered command: exit
[06:14:43.503 م] Registered command: player_sethealth
[06:14:43.504 م] Registered command: player_setmaxhealth
[06:14:43.504 م] Registered command: player_setimmunity
[06:14:43.501 م] Registered command: player_setmaxstamina
[06:14:43.507 م] Registered command: player_setspeed
[06:14:43.508 م] Registered command: player_changecolour
[06:14:43.509 م] Registered command: player_changestyle
[06:14:43.505 م] Registered command: player_setlevel
[06:14:43.512 م] Registered command: player_addmelee
[06:14:43.513 م] Registered command: player_addring
[06:14:43.495 م] Registered command: hide
[06:14:43.515 م] Registered command: out_melee
[06:14:43.517 م] Registered command: newitem
[06:14:43.517 م] Registered command: world_settime
[06:14:43.495 م] Registered command: show
[06:14:43.518 م] Registered command: world_freezetime
[06:14:43.519 م] Registered command: world_setday
[06:14:43.520 م] Registered command: world_downminelevel
[06:14:43.521 م] Registered command: world_setminelevel
[06:14:43.519 م] Registered command: world_setseason
[06:14:43.516 م] Registered command: out_rings
[06:14:43.514 م] Registered command: out_items
[06:14:43.510 م] Registered command: player_additem
[06:14:43.522 م] Found Manifest: C:\Users\HP\Desktop\Games\Stardew valley\Mods\NPCMapLocations\manifest.json
[06:14:43.532 م] Created psconfigs directory @C:\Users\HP\Desktop\Games\Stardew valley\Mods\NPCMapLocations\psconfigs
[06:14:43.606 م] Loading Mod DLL...
[06:14:43.606 م] LOADED MOD: NPC Map Locations Mod by Bouhm - Version StardewModdingAPI.Version | Description: Shows NPC locations on the map (@ C:\Users\HP\Desktop\Games\Stardew valley\Mods\NPCMapLocations\NPCMapLocations.dll)
[06:14:43.625 م] Found Manifest: C:\Users\HP\Desktop\Games\Stardew valley\Mods\TimeSpeed\manifest.json
[06:14:43.649 م] Created psconfigs directory @C:\Users\HP\Desktop\Games\Stardew valley\Mods\TimeSpeed\psconfigs
[06:14:43.651 م] Loading Mod DLL...
[06:14:43.660 م] LOADED MOD: TimeSpeed Mod by cantorsdust and Syndlig - Version StardewModdingAPI.Version | Description: Allows for a configurable ten minute tick length. (@ C:\Users\HP\Desktop\Games\Stardew valley\Mods\TimeSpeed\TimeSpeed.dll)
TimeSpeed Has Loaded
[06:14:43.713 م] Found Manifest: C:\Users\HP\Desktop\Games\Stardew valley\Mods\TrainerMod\manifest.json
[06:14:43.761 م] Created psconfigs directory @C:\Users\HP\Desktop\Games\Stardew valley\Mods\TrainerMod\psconfigs
[06:14:43.763 م] Loading Mod DLL...
[06:14:43.765 م] Registered command: save
[06:14:43.766 م] Registered command: load
[06:14:43.767 م] Registered command: exit
[06:14:43.764 م] Registered command: hide
[06:14:43.768 م] Registered command: player_setname
[06:14:43.769 م] Registered command: player_setmoney
[06:14:43.770 م] Registered command: player_setstamina
[06:14:43.770 م] Registered command: player_setmaxstamina
[06:14:43.772 م] Registered command: player_sethealth
[06:14:43.768 م] Registered command: stop
[06:14:43.763 م] Registered command: types
[06:14:43.774 م] Registered command: player_setlevel
[06:14:43.775 م] Registered command: player_setspeed
[06:14:43.775 م] Registered command: player_changecolour
[06:14:43.776 م] Registered command: player_changestyle
[06:14:43.777 م] Registered command: player_additem
[06:14:43.765 م] Registered command: show
[06:14:43.763 م] LOADED MOD: Trainer Mod by Zoryn - Version StardewModdingAPI.Version | Description: Registers several commands to use. Most commands are trainer-like in that they offer forms of cheating. (@ C:\Users\HP\Desktop\Games\Stardew valley\Mods\TrainerMod\TrainerMod.dll)
[06:14:43.780 م] Registered command: out_items
[06:14:43.772 م] Registered command: player_setmaxhealth
[06:14:43.778 م] Registered command: player_addring
[06:14:43.783 م] Registered command: out_rings
[06:14:43.783 م] Registered command: newitem
[06:14:43.785 م] Registered command: world_freezetime
[06:14:43.785 م] Registered command: world_setday
[06:14:43.773 م] Registered command: player_setimmunity
[06:14:43.787 م] Registered command: world_downminelevel
[06:14:43.788 م] Registered command: world_setminelevel
[06:14:43.789 م] LOADED 5 MODS
[06:14:43.790 م] SDV Loaded Into Memory
[06:14:43.778 م] Registered command: player_addmelee
[06:14:43.781 م] Registered command: out_melee
[06:14:43.784 م] Registered command: world_settime
[06:14:43.793 م] Applying Final SDV Tweaks...
[06:14:43.791 م] Initializing Console Input Thread...
[06:14:43.793 م] Registered command: help
[06:14:43.786 م] Registered command: world_setseason
[06:14:43.889 م] XNA Initialize
[06:14:44.580 م] Game failed to start: System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at new[](UInt32 )
   at Microsoft.Xna.Framework.Audio.UnsafeNativeMethods.AllocateArrayAndReadFile(String filename, Void** ppData, UInt32* pdwBufferSize)
   at Microsoft.Xna.Framework.Audio.UnsafeNativeMethods.WaveBank.CreateHandle(UInt32 hEngine, String string, Int32 length, IntPtr& pCleanup)
   at Microsoft.Xna.Framework.Audio.WaveBank..ctor(AudioEngine audioEngine, String nonStreamingWaveBankFilename)
   at StardewValley.Game1.Initialize()
   at StardewModdingAPI.Inheritance.SGame.Initialize()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at StardewModdingAPI.Program.RunGame()
System.ComponentModel.InvalidAsynchronousStateException: An error occurred invoking the method.  The destination thread no longer exists.
   at System.Windows.Forms.Control.WaitForWaitHandle(WaitHandle waitHandle)
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at StardewModdingAPI.Program.ConfigureSDV()
   at StardewModdingAPI.Program.Main(String[] args)

**Comment by jameelamir2005** [comment] 2016-04-03 15:15
It says game failed to start

**Comment by Kithio** [comment] 2016-04-03 15:22
Not sure if I'm seeing this right... but it looks like you're loading **NPC Map Locations** and **TrainerMod** twice..

[06:14:43.490 م] LOADED MOD: Trainer Mod by Zoryn - Version StardewModdingAPI.Version | Description: Registers several commands to use. Most commands are trainer-like in that they offer forms of cheating. (@ C:\Users\HP\AppData\Roaming\StardewValley\Mods\TrainerMod\TrainerMod.dll)

[06:14:43.763 م] LOADED MOD: Trainer Mod by Zoryn - Version StardewModdingAPI.Version | Description: Registers several commands to use. Most commands are trainer-like in that they offer forms of cheating. (@ C:\Users\HP\Desktop\Games\Stardew valley\Mods\TrainerMod\TrainerMod.dll)

Two different locations... Might be something to do with it? try removing them from one of the two places and try again.

**Comment by jameelamir2005** [comment] 2016-04-03 15:23
I'll try.

**Comment by jameelamir2005** [comment] 2016-04-03 15:29
Well, now this happens : *C:\Users\HP\AppData\Roaming\StardewValley\ErrorLogs\MODDED_ProgramLog.Log_LATEST.txt
Created log instance
[06:29:13.906 م] SDV Version: 1.0
[06:29:13.906 م] SMAPI Version: 0.39.6 Alpha
[06:29:13.918 م] Injecting New SDV Version...
[06:29:13.919 م] Starting SDV...
[06:29:13.911 م] Validating api paths...
[06:29:13.917 م] Initializing SDV Assembly...
[06:29:14.039 م] Patching SDV Graphics Profile...
[06:29:14.044 م] LOADING MODS
[06:29:14.044 م] Found Manifest: C:\Users\HP\Desktop\Games\Stardew valley\Mods\NPCMapLocations\manifest.json
[06:29:14.478 م] Created psconfigs directory @C:\Users\HP\Desktop\Games\Stardew valley\Mods\NPCMapLocations\psconfigs
TimeSpeed Has Loaded
[06:29:14.480 م] Loading Mod DLL...
[06:29:14.481 م] LOADED MOD: NPC Map Locations Mod by Bouhm - Version StardewModdingAPI.Version | Description: Shows NPC locations on the map (@ C:\Users\HP\Desktop\Games\Stardew valley\Mods\NPCMapLocations\NPCMapLocations.dll)
[06:29:14.543 م] Found Manifest: C:\Users\HP\Desktop\Games\Stardew valley\Mods\TimeSpeed\manifest.json
[06:29:14.817 م] LOADED MOD: TimeSpeed Mod by cantorsdust and Syndlig - Version StardewModdingAPI.Version | Description: Allows for a configurable ten minute tick length. (@ C:\Users\HP\Desktop\Games\Stardew valley\Mods\TimeSpeed\TimeSpeed.dll)
[06:29:14.824 م] Found Manifest: C:\Users\HP\Desktop\Games\Stardew valley\Mods\TrainerMod\manifest.json
[06:29:14.815 م] Created psconfigs directory @C:\Users\HP\Desktop\Games\Stardew valley\Mods\TimeSpeed\psconfigs
[06:29:14.815 م] Loading Mod DLL...
[06:29:14.850 م] Created psconfigs directory @C:\Users\HP\Desktop\Games\Stardew valley\Mods\TrainerMod\psconfigs
[06:29:14.852 م] Loading Mod DLL...
[06:29:14.852 م] LOADED MOD: Trainer Mod by Zoryn - Version StardewModdingAPI.Version | Description: Registers several commands to use. Most commands are trainer-like in that they offer forms of cheating. (@ C:\Users\HP\Desktop\Games\Stardew valley\Mods\TrainerMod\TrainerMod.dll)
[06:29:14.857 م] Registered command: types
[06:29:14.858 م] Registered command: load
[06:29:14.860 م] Registered command: exit
[06:29:14.861 م] Registered command: stop
[06:29:14.861 م] Registered command: player_setname
[06:29:14.862 م] Registered command: player_setmoney
[06:29:14.857 م] Registered command: show
[06:29:14.864 م] Registered command: player_setmaxstamina
[06:29:14.864 م] Registered command: player_sethealth
[06:29:14.858 م] Registered command: hide
[06:29:14.866 م] Registered command: player_setimmunity
[06:29:14.865 م] Registered command: player_setmaxhealth
[06:29:14.868 م] Registered command: player_setspeed
[06:29:14.857 م] Registered command: save
[06:29:14.869 م] Registered command: player_changestyle
[06:29:14.870 م] Registered command: player_additem
[06:29:14.870 م] Registered command: player_addmelee
[06:29:14.868 م] Registered command: player_changecolour
[06:29:14.872 م] Registered command: out_items
[06:29:14.872 م] Registered command: out_melee
[06:29:14.873 م] Registered command: out_rings
[06:29:14.863 م] Registered command: player_setstamina
[06:29:14.875 م] Registered command: world_settime
[06:29:14.876 م] Registered command: world_setday
[06:29:14.871 م] Registered command: player_addring
[06:29:14.866 م] Registered command: player_setlevel
[06:29:14.878 م] Registered command: world_setminelevel
[06:29:14.879 م] LOADED 3 MODS
[06:29:14.879 م] SDV Loaded Into Memory
[06:29:14.875 م] Registered command: world_freezetime
[06:29:14.881 م] Registered command: help
[06:29:14.882 م] Applying Final SDV Tweaks...
[06:29:14.878 م] Registered command: world_downminelevel
[06:29:14.877 م] Registered command: world_setseason
[06:29:14.880 م] Initializing Console Input Thread...
[06:29:14.874 م] Registered command: newitem
[06:29:14.974 م] XNA Initialize*
And it quits.

**Comment by jameelamir2005** [comment] 2016-04-03 15:40
Uhh help?

**Comment by jameelamir2005** [comment] 2016-04-03 15:46
If you could help me, you will save my life :/  I play this game so much and this is my only weekend, i have to study next day,please help me..

**Comment by jameelamir2005** [comment] 2016-04-03 15:48
Now red and grey text appear again.. C:\Users\HP\AppData\Roaming\StardewValley\ErrorLogs\MODDED_ProgramLog.Log_LATEST.txt
Created log instance
[06:47:34.455 م] SMAPI Version: 0.39.6 Alpha
[06:47:34.455 م] SDV Version: 1.0
[06:47:34.456 م] Validating api paths...
[06:47:34.468 م] Initializing SDV Assembly...
[06:47:34.469 م] Injecting New SDV Version...
[06:47:34.469 م] Starting SDV...
[06:47:34.606 م] Patching SDV Graphics Profile...
[06:47:34.612 م] LOADING MODS
[06:47:34.614 م] Found Manifest: C:\Users\HP\AppData\Roaming\StardewValley\Mods\CJBItemSpawner\manifest.json
[06:47:35.186 م] Created psconfigs directory @C:\Users\HP\AppData\Roaming\StardewValley\Mods\CJBItemSpawner\psconfigs
[06:47:35.223 م] Loading Mod DLL...
[06:47:35.224 م] LOADED MOD: CJB Item Spawner by CJ Bok - Version StardewModdingAPI.Version | Description: Simple in-game Item Spawner! (@ C:\Users\HP\AppData\Roaming\StardewValley\Mods\CJBItemSpawner\CJBItemSpawner.dll)
[06:47:35.226 م] Found Manifest: C:\Users\HP\Desktop\Games\Stardew valley\Mods\CJBItemSpawner\manifest.json
[06:47:35.269 م] Created psconfigs directory @C:\Users\HP\Desktop\Games\Stardew valley\Mods\CJBItemSpawner\psconfigs
[06:47:35.270 م] Loading Mod DLL...
[06:47:35.271 م] LOADED MOD: CJB Item Spawner by CJ Bok - Version StardewModdingAPI.Version | Description: Simple in-game Item Spawner! (@ C:\Users\HP\Desktop\Games\Stardew valley\Mods\CJBItemSpawner\CJBItemSpawner.dll)
[06:47:35.271 م] Found Manifest: C:\Users\HP\Desktop\Games\Stardew valley\Mods\TrainerMod\manifest.json
[06:47:35.335 م] Created psconfigs directory @C:\Users\HP\Desktop\Games\Stardew valley\Mods\TrainerMod\psconfigs
[06:47:35.337 م] Loading Mod DLL...
[06:47:35.337 م] LOADED MOD: Trainer Mod by Zoryn - Version StardewModdingAPI.Version | Description: Registers several commands to use. Most commands are trainer-like in that they offer forms of cheating. (@ C:\Users\HP\Desktop\Games\Stardew valley\Mods\TrainerMod\TrainerMod.dll)
[06:47:35.378 م] Registered command: save
[06:47:35.374 م] Registered command: show
[06:47:35.353 م] Registered command: hide
[06:47:35.382 م] Registered command: stop
[06:47:35.383 م] Registered command: player_setname
[06:47:35.383 م] Registered command: player_setmoney
[06:47:35.384 م] Registered command: player_setstamina
[06:47:35.385 م] Registered command: player_setmaxstamina
[06:47:35.386 م] Registered command: player_sethealth
[06:47:35.387 م] Registered command: player_setmaxhealth
[06:47:35.387 م] Registered command: player_setimmunity
[06:47:35.388 م] Registered command: player_setlevel
[06:47:35.390 م] Registered command: player_setspeed
[06:47:35.390 م] Registered command: player_changecolour
[06:47:35.391 م] Registered command: player_changestyle
[06:47:35.352 م] Registered command: types
[06:47:35.393 م] Registered command: player_addring
[06:47:35.393 م] Registered command: out_items
[06:47:35.394 م] Registered command: out_melee
[06:47:35.381 م] Registered command: exit
[06:47:35.398 م] Registered command: newitem
[06:47:35.379 م] Registered command: load
[06:47:35.400 م] Registered command: world_freezetime
[06:47:35.400 م] Registered command: world_setday
[06:47:35.392 م] Registered command: player_addmelee
[06:47:35.402 م] Registered command: world_downminelevel
[06:47:35.403 م] Registered command: world_setminelevel
[06:47:35.403 م] LOADED 3 MODS
[06:47:35.404 م] SDV Loaded Into Memory
[06:47:35.405 م] Initializing Console Input Thread...
[06:47:35.406 م] Registered command: help
[06:47:35.407 م] Applying Final SDV Tweaks...
[06:47:35.392 م] Registered command: player_additem
[06:47:35.401 م] Registered command: world_setseason
[06:47:35.399 م] Registered command: world_settime
[06:47:35.395 م] Registered command: out_rings
[06:47:35.548 م] XNA Initialize
[06:47:36.273 م] Game failed to start: System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at new[](UInt32 )
   at Microsoft.Xna.Framework.Audio.UnsafeNativeMethods.AllocateArrayAndReadFile(String filename, Void** ppData, UInt32* pdwBufferSize)
   at Microsoft.Xna.Framework.Audio.UnsafeNativeMethods.WaveBank.CreateHandle(UInt32 hEngine, String string, Int32 length, IntPtr& pCleanup)
   at Microsoft.Xna.Framework.Audio.WaveBank..ctor(AudioEngine audioEngine, String nonStreamingWaveBankFilename)
   at StardewValley.Game1.Initialize()
   at StardewModdingAPI.Inheritance.SGame.Initialize()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at StardewModdingAPI.Program.RunGame()
System.ComponentModel.InvalidAsynchronousStateException: An error occurred invoking the method.  The destination thread no longer exists.
   at System.Windows.Forms.Control.WaitForWaitHandle(WaitHandle waitHandle)
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke(Delegate method)
   at StardewModdingAPI.Program.ConfigureSDV()
   at StardewModdingAPI.Program.Main(String[] args)

**Comment by jameelamir2005** [comment] 2016-04-03 15:48
Please help!

**Comment by jameelamir2005** [comment] 2016-04-03 15:49
:cry:

**Comment by speeder** [comment] 2016-04-03 15:51
ah, you bumped into the SDV bug, it sometimes happen.

Wait for CA to make a official 1.07 :(

The complaint you saw earlier in your log (audio engine failure), is a SDV bug, not SMAPI bug.

Here in the reddit changelog of beta 1.07

" potential bug fix for an audio engine path problem that prevented the game from starting "

**Comment by Kithio** [comment] 2016-04-03 15:53
pretty sure 1.07 is in the "BETA" branch of the game.

**Comment by jameelamir2005** [comment] 2016-04-03 15:57
Excuse me guys?I cannot understand a word.. What should i do?

**Comment by speeder** [comment] 2016-04-03 16:09
Stardew Valley (the game) that is broken, not SMAPI.

You should wait  for the game to update, I believe this will happen on monday or tuesday.

**Comment by jameelamir2005** [comment] 2016-04-03 16:10
Wait dude... I can't get the update, I've just downloaded it from pirating...

**Comment by jameelamir2005** [comment] 2016-04-03 16:10
Ahh thanks anyways. :disappointed:

**Comment by jameelamir2005** [comment] 2016-04-03 16:14
Is there any way i can fix it?

**Comment by ClxS** [comment] 2016-04-03 16:55
Hi @jameelamir2005, @speeder is right that the issue is caused by you using the test version of Stardew and there's no plans to update SMAPI to work with the beta version yet. Issues may also be caused by using the pirated version of the game - something I'm not going to really fix.

I realise you're only young (11?) so probably wont be in a position where you can buy the game, so I suggest just waiting. You don't really need to play with mods yet since no big game changing mods exist yet.

**Comment by CJBok** [comment] 2016-04-05 13:49
@jameelamir2005 in the log it says you are using verion 1.0 of stardew valley. The current versions of SMAPI are not supported for that version. I recommend you update Stardew Valley to version 1.07 as this has been released today.

**Closed by CJBok** 2016-04-05 13:49 UTC
