### ISSUE TITLE
Mac/Linux support?

### ISSUE THREAD

**Issue by LuciousLisa** [ClxS/SMAPI#126] opened 2016-08-06 08:27 UTC
Now that the game has become available to us non-Windows users, it would be appreciated a lot if SMAPI also offers support for these operating systems. Pretty please? :)

**Comment by Mighty-squid-50** [comment] 2016-08-07 07:50
I do agree. It seems to only work with Microsoft .NET Framework 4.6.1. I guess we just have to wait.

**Comment by kozie** [comment] 2016-08-09 11:19
+1 here 👍

**Comment by Katorone** [comment] 2016-08-13 09:58
+1 please.

**Comment by emileechen** [comment] 2016-08-16 03:56
+1

**Comment by MacLeek** [comment] 2016-08-21 02:41
Guys,I've managed to make it work on Mac.    
Here's my fork  
https://github.com/MacLeek/SMAPI  
And instructions here https://www.reddit.com/r/StardewValley/comments/4ypp1a/so_this_is_the_smapi_for_mac/

**Comment by kozie** [comment] 2016-08-21 12:37
I got an error tho, saying system.windows.forms could not be found when trying to run the StardewModdingAPI.bin.osx from terminal.

I checked out the original SMAPI, removed the xna refs and added the ones according to your instructions. Also removed the ref to system.windows.forms, altered to code according to your fork and built it. It seems to load up now but it's still throwing errors at me in terminal about system.* stuff.

**Comment by MacLeek** [comment] 2016-08-22 01:00
@kozie The stardew_mac is the project which I decompiled from stardewvalley.exe for easier debugging,I just forgot to remove it and also system.windows.forms.   
I mainly removed the code which was not used in current version like forms and other variables.  
For the threading part,I found with the original code the game window is not active and I can not move my mouse and click a button although the game is actually running.After several attempts, when I made the game running in the main thread and also start the console thread, I found it worked.  
Actually I'm really new to c# programming,just started a week a ago and only know some basic grammer:stuck_out_tongue: So if I ever  misunderstood something,please point it out.

**Comment by kozie** [comment] 2016-08-22 06:27
Sounds quite logic ^_^

I hope that the maintainers of the project are seeing this and will take actions.

**Comment by LuciousLisa** [comment] 2016-08-22 21:31
I love that you started working on a fork, @MacLeek, but maybe keep further comments about that version contained to its issue list so as not to confuse the maintainer of this one? Thanks! :)

**Comment by xubiod** [comment] 2016-08-24 13:36
can linux support be made please? my only computer that can run the game has ubuntu. +10 to whoever makes a linux port of this

**Comment by kozie** [comment] 2016-08-25 07:45
I got an Ubuntu 14.04 box running with Vagrant. It seems to work quite nice so i might try using that if no one else will do :)

**Comment by ClxS** [comment] 2016-08-25 12:15
I don't really have enough time to add official OSX/Linux support at the moment, especially since I have very little experience with either.
I'd recommend checking out the forks from people who've added the support themselves, like MacLeek's or the Linux compatible version on the Official forums.

**Comment by kozie** [comment] 2016-08-28 12:43
I have a linux version which seems to work :)

It can be downloaded from my dropbox (https://dl.dropboxusercontent.com/u/3946199/sdv/StardewModdingAPI_linux_x86_64.zip).

- Copy the files from the zip to the StardewValley folder (`~/.steam/steam/steamapps/common/Stardew\ Valley/`)
- Copy `StardewValley.bin.x86_64` (or `StardewValley.bin.x86`) and name it `StardewModdingAPI.bin.x86_64` (or `StardewModdingAPI.bin.x86_64`)
- Run the game from terminal with `./StardewModdingAPI.bin.x86_64` (or `./StardewModdingAPI.bin.x86`)

To run it from steam i guess you have to edit the file `StardewValley` and change the last few lines from `StardewValley.bin.x86_64` to `StardewModdingAPI.bin.x86_64`. I haven't tested that tho, but it seems it's the same as the instructions from Macleek for MacOS.

**Comment by x3ro** [comment] 2016-09-11 12:06
Hi @kozie, do you mind sharing how you managed to build it? Can you share instructions and, if necessary, the source changes?

**Comment by kozie** [comment] 2016-09-11 12:13
Hi @x3ro, i did not do much extra using @MacLeek's instructions and repo.

I just opened his solution in monodev, removed the windows.system.form stuff, added the correct references for SDV and MonoGame framework and built using 'Release'.
Copy over the necessary files over to the SDV folder and it worked ^_^

**Comment by Mighty-squid-50** [comment] 2016-09-16 03:40
I have been trying to install CJB Cheat Menu (don't judge me :) but I keep getting : 

![image](https://cloud.githubusercontent.com/assets/18133805/18574701/4eb5d344-7c02-11e6-9497-0e24c6748ae1.png)

**Comment by kozie** [comment] 2016-09-16 07:09
You might want to try to recompile the plugin if the source is available tho. Could be that alternate packages are needed for the "missing classes".

**Comment by pietrondo** [comment] 2016-09-20 14:39
+1 linux.. . I have tried with wine but problem because I use linux native client.

**Comment by pietrondo** [comment] 2016-09-20 14:41
@kozie the file in your dropbox folder are exe..

**Comment by kozie** [comment] 2016-09-20 14:43
Yep, that's right. As are the official SDV binary files for Linux and MacOs
themselves.

**Comment by kozie** [comment] 2016-09-20 15:54
I haven't tried much but some seem to work out of the box and some won't.

Out of experience, I think that most mods need to be recompiled.

It would be much better if SMAPI would've had something like LUA so only
SMAPI would've been made crossplatform and all mods would be the same :)

**Comment by pietrondo** [comment] 2016-09-20 15:58
okk.. how can I compile them.. I have tried with LookupAnything
but it give me errors like: `Framework/Targets/GenericTarget.cs(99,100): error CS0246: The type or namespace name `Texture2D' could not be found. Are you missing an assembly reference?
`

**Comment by Pathoschild** [comment] 2016-09-22 01:43
Hi @pietrondo. I'm the developer of [Lookup Anything](http://www.nexusmods.com/stardewvalley/mods/541); I stumbled across this thread looking into Linux support. :)

Before compiling the mod, you need to update the path to the game directory. The README in the latest release has a [section about compiling the mod](https://github.com/Pathoschild/LookupAnything#compiling-the-mod) which may help. I don't have Linux myself, but I'd be happy to upload a Linux build to Nexus Mods if you can compile it. If there are code changes required, feel free to submit a pull request.

**Comment by pietrondo** [comment] 2016-09-27 16:37
@Pathoschild  thx
But I don't find <GamePath> in the LookupAnything.csproj

**Comment by pietrondo** [comment] 2016-09-27 16:43
@Pathoschild  found it.. (i have updated my github version of the mod)

**Comment by ReidE96** [comment] 2016-10-04 00:33
I guess with 1.1 this is going to be more than a little bit different, and hopefully easier to implement?

**Comment by rumangerst** [comment] 2016-10-12 15:12
1.1 unfortunately wasn't the update that made it easier for cross-platform mods :(

But I now created a new mod manager that is able to compile DLL-mods on the user's computer. It is able to run `nuget restore`, msbuild/xbuild, translate between XNA and MonoGame and set the correct hit-paths for assemblies. Mod-developers can encrypt their source (to make it harder to steal it).

 I was able to make a package for it that successfully builds SMAPI on Windows. But on Linux and Mac, it's building, but not working.

I have some examples, including SMAPI (only runs on Windows and is marked as such), STORM (which doesn't run) and Renovated Farms (working).

Something interesting regarding cross-platform is that the executable is called "Stardew Valley.exe" on Windows and "StardewValley.exe" on other platforms :/ 
The mod manager solves this by just copying "Stardew Valley.exe" to "StardewValley.exe"

https://github.com/rumangerst/SilVerPLuM

**Comment by vizv** [comment] 2016-10-16 04:58
Here is my fork trying to change minimum amount of code to make it works for Linux.
I don't own a Mac, so sorry :P

https://github.com/vizv/SMAPI/releases

**Comment by vizv** [comment] 2016-10-16 05:24
@Pathoschild Also your LookupAnything, a really awesome mod!

https://github.com/vizv/LookupAnything/releases

**Comment by ReidE96** [comment] 2016-10-16 05:37
@vizv While you're on a roll, odds of tackling Timespeed or an equivalent? ;)

**Comment by Pathoschild** [comment] 2016-10-16 05:40
@vizv: that's awesome, especially open-sourcing your Linux/Mac version of SMAPI. Thanks!

I'm working on an open-source guide to modding; I'll get some Linux/Mac players to beta-test Lookup Anything for a while, and if everything checks out I'll link your download as the main SMAPI for Linux/Mac. I think we can get the ball rolling on Linux/Mac mods. :)

**Comment by vizv** [comment] 2016-10-16 06:20
Just port another mod I use: NPC Map Locations.

https://github.com/vizv/StardewValleyMods

@ReidE96 I'd try that.
@Pathoschild If I can borrow a Mac tomorrow I'll try to compile it in OS X. I have test it around with these two mods and I do experience lagging sometimes, but it's playable.

**Comment by ReidE96** [comment] 2016-10-16 06:25
@vizv Shiny! Happy to help with compiling things on Mac if there's a quick buildenv setup guide I can grab ahold of, though I'm not going to have a lot of time to test stability during play just now.

**Comment by vizv** [comment] 2016-10-16 06:34
@ReidE96 tomkrizan already got a working release here, I just tested it:

https://github.com/tomkrizan/TimeSpeed/releases

**Comment by ReidE96** [comment] 2016-10-16 07:09
Oh, awesome! Guess the next task then is to get things merged into mainline with some platform-detecting conditionals so it's not per-OS installs :D

**Comment by ReidE96** [comment] 2016-10-16 07:26
@vizv Alrighty, just tried running on Mac, crashes out immediately over System.Windows.Forms - not sure if there's a rogue check, or Monogame doesn't want to play as nicely on Mac. Gonna go grepping and see what I find.

**Comment by ReidE96** [comment] 2016-10-16 07:32
@vizv Looks like it's pathing on the tweaked SMAPI. Mac is ~\Library\Application Support\Steam\SteamApps\common\Stardew Valley\Contents\MacOS\ for the game folder, rather than ~\.local\share\Steam[etc]

**Comment by vizv** [comment] 2016-10-16 07:36
@ReidE96 I'm new for C# and monodevelop (just installed it for two days and have no C# development experience), not sure how to fix it in OS X. But if you got monodevelop for OS X, go to reference and fix the broken references by selecting dll/exe assemblies, it might fix the compiling issue.

**Comment by ReidE96** [comment] 2016-10-16 07:37
@vizv 'Fraid I don't have it installed, but if I can find time tomorrow I'll do so. Should hopefully be an easy fix!

**Comment by rumangerst** [comment] 2016-10-16 10:23
@vizv Thank you for making this port! Seems to work (at least it starts). Although for me the game refuses to exit (must kill it).

I updated the [SMAPI example](https://github.com/rumangerst/SilVerPLuM/tree/master/examples) with your linux release. Compiles and works for me.

**Comment by pietrondo** [comment] 2016-10-16 16:18
thx.. but for example:
how Can I add this mod http://www.nexusmods.com/stardewvalley/mods/541/ ?
thx


Pietro Capriata

http://www.pietrocapriata.me


CONFIDENTIALITY DISCLAIMER
Le informazioni contenute in questo messaggio di posta elettronica e negli
allegati sono riservate e confidenziali e ne sono vietate la lettura,
l'uso, la copia, la comunicazione e la diffusione in qualunque modo
eseguite. Qualora lei non fosse la persona destinataria del messaggio, la
invitiamo ad eliminarlo, dando gentilmente comunicazione al mittente
tramite e-mail di ritorno.

The information contained in this email message and any files transmitted
with it are confidential and privileged and any reading, processing,
distribution or copy of this material is strictly prohibited, in any form.
If you are not the intended recipient of this message, please immediately
delete it, giving the relevant communication to the sender by reply e-mail.

**Comment by ReidE96** [comment] 2016-10-16 16:35
@pietrondo You have to compile it for mono instead of .net - vizv posted a link above to a version working with this version of SMAPI (https://github.com/tomkrizan/TimeSpeed/releases)

**Comment by ReidE96** [comment] 2016-10-16 16:50
@pietrondo Sorry, copied the wrong link, https://github.com/vizv/LookupAnything/releases was the one I meant

**Comment by vizv** [comment] 2016-10-16 18:16
@pietrondo I have already release the Linux version, https://github.com/vizv/LookupAnything/releases, just drop to your Mods directory.

**Comment by pietrondo** [comment] 2016-10-16 18:17
thx!

**Comment by vizv** [comment] 2016-10-19 00:08
@ReidE96 I borrowed a Mac last night, but unfortunately it compiles but not work correctly. One of the problem is `System.Windows.Forms` not working correctly in OS X, which I have masked them in the code. Then it compiles and run, I can see the graphics and game screen but I can't click anything. Commands in console works but cursor always busy when pointing to the game screen. There a one error message on the console says something about late swap not supported.

Guess OS X needs a little more tweaks, I gave up. Maybe refer to MacLeek's fork see how to get everything working.

**Comment by Pathoschild** [comment] 2016-10-21 04:45
I spent a few days working on this, and here's my progress so far.

- Crossplatform modding is now documented!
  - See _[using mods](http://canimod.com/guides/using-mods)_ for a guide to using mods on Linux, Mac, and Windows.
  - See _[creating a SMAPI mod](http://canimod.com/guides/creating-a-smapi-mod)_ for a guide to creating a SMAPI mod that compiles on all platforms.
- I created a NuGet package which lets mod authors compile their mods _without changes_ on Linux, Mac, and Windows. It detects the current platform and injects the right references & build configuration. It's documented in the _[creating a SMAPI mod](http://canimod.com/guides/creating-a-smapi-mod)_ guide.

This is still experimental; let me know if you have any problems following the guides.

The next versions of Chests Anywhere and Lookup Anything will be officially released on all platforms, and I'll be working with mod authors to transition them to crossplatform mods.

**Comment by x3ro** [comment] 2016-10-23 00:01
> @ClxS: I don't really have enough time to add official OSX/Linux support at the moment, especially since I have very little experience with either.

Would you be open to having contributors supply PRs for the necessary changes? I think that it'd be hugely beneficial to the modding community if there weren't different SMAPI versions/releases for different platforms, as that would make it even harder to write mods for all platforms.

**Comment by alexb5dh** [comment] 2016-10-23 15:35
@Pathoschild, thanks for the package. It greatly simplifies cross-platform building.

Does copying game binaries to ouput directory is necessary? Adding `<Private>false</Private>` to each `<Reference>` should prevent this. You can than zip mod from output as build step with the help of [MSBuild Extension Pack](https://github.com/mikefourie/MSBuildExtensionPack).

**Comment by Pathoschild** [comment] 2016-10-24 15:14
@alexb5dh Thanks for the suggestion! The latest 1.2 release marks the imported dependencies private.

I'll hold off on zipping the mod automatically for now. The [MSBuild Extension Pack](https://github.com/mikefourie/MSBuildExtensionPack) uses a compiled DLL and they make no mention of crossplatform compatibility, so it's likely Windows-only. It's also a large project, so I wouldn't want to require it just for one thing. (The mod developer is free to add their own task to do it, of course.)

**Comment by Pathoschild** [comment] 2016-10-25 21:59
@vizv your [SMAPI for Linux release](https://github.com/vizv/SMAPI/releases) has a different internal version (`0.40.0 1.1`) than the official build (`0.40.0 1.1-3`), which complicates version checks in mods. Could you upload a new version that matches the official version?

**Comment by vizv** [comment] 2016-10-26 00:57
@Pathoschild I'll look into that.

**Comment by Pathoschild** [comment] 2016-10-26 03:53
[Chests Anywhere](http://www.nexusmods.com/stardewvalley/mods/518/) and [Lookup Anything](http://www.nexusmods.com/stardewvalley/mods/541/) are now officially supported on Linux, Mac, and Windows!

Next is SMAPI itself.

**Comment by vizv** [comment] 2016-10-26 09:00
@Pathoschild I checked that, the problem is: on https://github.com/cjsu/SMAPI/releases/tag/0.40.1.1 it claims the release is build against 5087c3d but it is not (at least 12e4822), I'll rebase the master and build it again.

**Comment by vizv** [comment] 2016-10-26 09:16
@Pathoschild The updated version `0.40.0 1.1-3` is live: https://github.com/vizv/SMAPI/releases/tag/0.40.1.1

**Comment by Pathoschild** [comment] 2016-10-26 15:17
@vizv Thanks!

**Comment by Pathoschild** [comment] 2016-10-27 16:39
I have a beta version of SMAPI that runs on Linux, Mac, and Windows. This will become an official release if all goes well. I just need some volunteers to try it out — the more the better!

If you have any questions or problems, feel free to [come chat directly on Discord](https://discord.gg/KCJHWhX).

## 1. Remove unofficial versions of SMAPI
_If you've never used SMAPI on Linux or Mac, you can skip this section._

The unofficial SMAPIs for Linux/Mac replace your game launcher. The beta adds a separate launcher instead so you can easily go back to playing without mods (just like the current version on Windows). You should restore the original launcher to prevent confusion later.

If you created a `StardewValley.unmodded` file based on the [_using mods_ guide](http://canimod.com/guides/using-mods):

1. Delete the `StardewValley` file without an extension (don't delete `StardewValley.exe`!).
2. Rename `StardewValley.unmodded` to `StardewValley`.

Otherwise:

1. Delete the `StardewValley` file without an extension (don't delete `StardewValley.exe`!).
2. Unpack [the default launcher](https://github.com/cjsu/SMAPI/files/556162/StardewValley.launcher.zip) into your game directory.

## 2. Install the beta
1. Unpack  [SMAPI 0.41-beta](https://github.com/Pathoschild/SMAPI/releases/tag/0.41) directly into your game folder (e.g. `StardewModdingAPI.exe` should be in the same folder as `Stardew Valley.exe`).

   These are the default game folders:

   platform | path |
   :----|:----|
   GOG on Linux | ~/GOG Games/Stardew Valley/game
   GOG on Windows | C:\Program Files (x86)\GalaxyClient\Games\Stardew Valley
   Steam on Linux | ~/.local/share/Steam/steamapps/common/Stardew Valley
   Steam on Mac | ~/Library/Application Support/Steam/steamapps/common/Stardew Valley/Contents/MacOS
   Steam on Windows | C:\Program Files (x86)\Steam\steamapps\common\StardewValley

## 3. Test the beta
1. Unpack the [Lookup Anything mod](http://nexusmods.com/stardewvalley/mods/541) into the `<game folder>\Mods` folder. (It works on all platforms, so it's a good baseline.)
2. Launch SMAPI to play with mods. (On Linux or Mac, run `StardewModdingAPI` without an extension. On Windows, run `StardewModdingAPI.exe`.)
3. In the game, point the cursor at your character and press `F1`. Does something like [this screenshot](https://raw.githubusercontent.com/Pathoschild/LookupAnything/1.6/screenshots/player.png) appear?
4. Add a comment with your results (even if it worked fine!). Don't forget to mention whether you play on Linux, Mac, or Windows.

If that didn't work, [come chat directly on Discord](https://discord.gg/KCJHWhX) so we can figure out why. If don't want to use Discord, add a comment here [with the information needed to look into it](http://canimod.com/guides/asking-for-help).

## 4. Uninstall the beta (optional)
Just delete these files in your game folder:
* `Mods` folder
* `StardewModdingAPI.exe`
* `StardewModdingAPI.pdb` (Windows) or `StardewModdingAPI.mdb` (Linux or Mac)
* `StardewModdingAPI` (linux or Mac only)
* `Newtonsoft.Json.dll` (Linux or Mac only)

**Comment by rumangerst** [comment] 2016-10-27 17:42
Tested Pathoschild's build on Linux (Manjaro KDE). 

* SMAPI loads
* Chests Anywhere (also cross-platform by Pathoschild) works
* Lookup Anything (also cross-platform by Pathoschild) works

Installed with Silverplum without compilation (just installing the mods). Available in repository Repository List -> Silverplum ported repository

**Comment by ajrc0re** [comment] 2016-10-27 18:18
Any word on the cheatmenu mod? Seems like a really popular one thats been completely abandoned. Would be nice to see someone pick it up and get it working in linux! If theres instructions on how to get it working in linux I could even do it myself but I only see instructions for making a new mod to work with linux (as opposed to converting an existing mod)

**Comment by Pathoschild** [comment] 2016-10-27 18:37
@ajrc0re you can [migrate an existing mod using the crossplatform build config](https://github.com/Pathoschild/Stardew.ModBuildConfig#installation), but you'll need the mod's source code.

**Comment by Pathoschild** [comment] 2016-10-27 19:24
I made several changes for Mac compatility and updated the downloads; thanks @mys721tx for helping test on Mac. :)

**Comment by mys721tx** [comment] 2016-10-27 20:03
Here are the test results of the 0.41-beta on a Max OS X 10.12.1 box.

80b2b3d: Unable to launch SMAPI due to missing System.Windows.Forms ([log](https://gist.github.com/mys721tx/2c0391b2b3f30363f9205ab4dab777aa/282405620be561e1e4a2d7053a7dba6c4ba83b17))
f44eb6d: Unable to load mods from SMAPI due to missing System.Numerics ([log](https://gist.github.com/mys721tx/2c0391b2b3f30363f9205ab4dab777aa/04262bc50fae9af8b163179fe2d538e83a4f213d))
58c0262: Game runs in the background due to threading ([log](https://gist.github.com/mys721tx/2c0391b2b3f30363f9205ab4dab777aa/74655ce2bb5f9da7b5e838c058a4eb9d6500a33f))
6cc8c6d: Everything works!

**Comment by ajrc0re** [comment] 2016-10-27 23:19
Been trying to get the new SMAPI working for the last few hours. Definitely doesnt work. Heres my error log, not really sure what the issue is but you can see everal errors that complain about "System.IO.FileNotFoundException: Could not load file or assembly or one of its dependencies."


[MODDED_ProgramLog.Log_LATEST.txt](https://github.com/cjsu/SMAPI/files/557250/MODDED_ProgramLog.Log_LATEST.txt)

Arch Linux (Antergos)
KDE Plasma
lastest version of SV (1.11)
Latest SMAPI 0.41 Beta

**Comment by mys721tx** [comment] 2016-10-27 23:31
@ajrc0re It looks like System.Numerics is missing. Could you try `System.Numerics.dll` from mono?

**Comment by Pathoschild** [comment] 2016-10-27 23:39
@ajrc0re: I updated the Linux release to fix that error on some distros; let me know if the new build works.

**Comment by ajrc0re** [comment] 2016-10-27 23:49
Worked flawlessly, thanks for your help! Great work everyone.

**Comment by vizv** [comment] 2016-10-28 01:38
@Pathoschild Great job! One last problem, if you don't change the game launcher how to launch it with Steam integration (such as Steam overlay)?

**Comment by Pathoschild** [comment] 2016-10-28 01:42
@vizv you can [configure Steam to launch SMAPI directly on Windows](http://canimod.com/guides/using-mods#on-windows); I assume you can do the same on Linux and Mac. If someone can figure out the equivalent on those platforms, I'll add it to the guide.

**Comment by vizv** [comment] 2016-10-29 19:39
@Pathoschild I tried before but it doesn't seem to work, could you confirm that?

**Comment by Pathoschild** [comment] 2016-10-29 19:45
@vizv yep, just confirmed with @rumangerst that it works on Linux too.

**Comment by vizv** [comment] 2016-10-29 21:20
@Pathoschild I put `"/path/to/StardewModdingAPI" %command%` to launch option, and it not always work. When I launch steam through terminal, it works. But when I open it by clicking steam icon, it doesn't. Wondering why... Is there anyone have the similar issue? Or did I do something wrong.

**Comment by rumangerst** [comment] 2016-10-29 21:23
@vizv Could be caused by Steam having problems to run shell scripts. It may give the command to the underlying BASH if you run it in Terminal, but otherwise it expects an actual executable. Maybe wrapping everything in bash -c works.
I had to do the same for Silverplum. It wraps all shell scripts (like SDV) in BASH.

**Comment by vizv** [comment] 2016-10-29 21:52
@rumangerst you mean I put `bash -c '"/path/to/StardewModdingAPI" %command%'` in launch option? But it doesn't work. I have no idea about how steam handle value in launch option.

**Comment by rumangerst** [comment] 2016-10-29 23:28
@vizv Indeed seems to not work with BASH. But the original approach works for me. Steam started in terminal and via desktop file. Very strange.

What distribution are you using?

**Comment by vizv** [comment] 2016-10-29 23:31
@rumangerst Gentoo/KDE5/fish shell

I think mono crashes after launch from desktop file, but I can't get stacktrace/log/anything.

**Comment by rumangerst** [comment] 2016-10-29 23:38
@vizv There must be something that's different between Steam via desktop and Steam via terminal ... I only know that Steam starts something with /bin/sh.

**Comment by vizv** [comment] 2016-10-29 23:44
@rumangerst I did a `ps aux |grep Stardew` for both starting steam via shell and desktop, and the output are exactly the same...

**Comment by rumangerst** [comment] 2016-10-29 23:55
@vizv Now I'm out of options.
Maybe try chainloading with Silverplum

**Comment by Pathoschild** [comment] 2016-10-30 19:23
The reason for a separate launcher is to make it easy to go back to normal gameplay (without needing to redownload core files). I think that's a good idea, but not if it makes installation difficult (e.g. the last several comments).

Before we go live with crossplatform SMAPI, I think we should consider creating simple install/uninstall scripts to automate the manual install. The install scripts would...

1. detect the game install path (or ask the user if it can't be found);
2. rename the default `StardewValley` launcher to `StardewValley-without-mods` (if it doesn't already exist);
3. copy the SMAPI files into the game directory.

The uninstall scripts would...

1. detect the game install path (or ask the user if it can't be found);
2. delete all SMAPI files (but leave the non-default mods just in case);
3. rename the `StardewValley-without-mods` launcher to `StardewValley`.

Any thoughts?

**Closed** 2016-10-30 20:48 UTC
Labels: enhancement

**Comment by Pathoschild** [comment] 2016-10-30 20:53
SMAPI will be crossplatform in the upcoming 1.0 release; installer proposal moved to #155.
